# Generated by Django 5.1.5 on 2025-01-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUser',
            new_name='CustomUser',
        ),
    ]
